POST http://127.0.0.1:8000/login
Content-Type: application/json 

{ "username": "test5", "password": "password123" }

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json 

{ "username": "test5", "password": "password123", "email": "test@gmail.com" }

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json 
Authorization: Token 08147787ac14e3980122077f9e2423dac653e7e4

{}

###

GET http://127.0.0.1:8000/logout
Content-Type: application/json 
Authorization: Token 08147787ac14e3980122077f9e2423dac653e7e4
